version: "3.8"

services:
  app:
    volumes:
      - $GOPATH/pkg/mod:/go/pkg/
      - ./logs/app:/app/logs/app
    build: ./
    network_mode: "host"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
  db:
    image: postgres:latest
    command: ["postgres",
              "-c", "log_directory=/var/log/postgresql",
              "-c", "logging_collector=on",
              "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: hack_23
      POSTGRES_PASSWORD: password_admin
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
      - ./logs/postgres:/var/log/postgresql

  cache:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data

volumes:
  db_data:
    driver: local
  cache:
    driver: local

